---
AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: >
  test-apis

# Parameters are populated atm with the default values
Parameters:
  Environment:
    Description: Environment to run under
    Type: String
    Default: "local"
    AllowedValues:
      - "local"
      - "qa"
      - "prod"
  LocalEnvironmentType:
    Description: Type of Local Environment to run under
    Type: String
    Default: "one"
    AllowedValues:
      - "one"
      - "two"
  PassedInParameter:
    Description: An example parameter passed into the template
    Type: String
    Default: ""

# Environment mapped variables
Mappings:
  LocalEnvironmentSettings:
    one:
      DependencyUrl: 'http://172.17.0.1:3001/local/one/dependency'
    two:
      DependencyUrl: 'http://host.docker.internal:3001/local/two/dependency'
  Environments:
    local:
      DependencyUrl: 'http://host.docker.internal:3001/local/dependency'
    qa:
      DependencyUrl: 'http://172.17.0.1:3001/qa/dependency'
    prod:
      DependencyUrl: 'http://my.server.com:3001/prod/dependency'

# apply some conditions
Conditions:
  LocalEnvironment: !Equals [ !Ref Environment, 'local' ]
  NotLocalEnvironment: !Not [ !Equals [ !Ref Environment, 'local' ] ]

# Global function env vars
Globals:
  Api:
    Cors:
      AllowMethods: 'OPTIONS'
  Function:
    Environment:
      Variables:
        DEPENDENCY_URL: !FindInMap [Environments, !Ref Environment, DependencyUrl]
        # the if will get resolved
        DEPENDENCY_URL_IF: !If [
          LocalEnvironment,
          !FindInMap [LocalEnvironmentSettings, !Ref LocalEnvironmentType, DependencyUrl],
          !FindInMap [Environments, !Ref Environment, DependencyUrl]
        ]
        MY_PARAMETER_VARIABLE:
          Ref: PassedInParameter
        MY_SECRET:
          Fn::Sub: "{{resolve:secretsmanager:${SecretType}:SecretString:secretValue}}"
    Runtime: nodejs14.x
    Timeout: 15
    Layers:
      - !Ref BaseLayer

# Http API Gateway and Resources
Resources:
  # http api with routes defined on function events,
  # events are routed through the auth function first
  TestHttpApiv1:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt lambdaAuthorizer.Arn
      CorsConfiguration: true
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      StageName: v1

  # http api with routes defined on function events
  TestHttpApiv2:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: SimpleLambdaRequestAuthorizer
        Authorizers:
          SimpleLambdaRequestAuthorizer:
            FunctionArn: !GetAtt simpleLambdaAuthorizer.Arn
            EnableSimpleResponses: true
            Identity:
              Headers:
                - Authorization
      CorsConfiguration: 'localhost'
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      StageName: v2

  # http api with token authorizer
  TestHttpApiv3:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: SimpleLambdaRequestAuthorizer
        Authorizers:
          SimpleLambdaRequestAuthorizer:
            FunctionArn: !GetAtt simpleLambdaAuthorizer.Arn
            EnableSimpleResponses: true
      CorsConfiguration: true
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      StageName: v3

  # http api with external authorizer that will be ignored
  TestHttpApiv4:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: ExternalAuthorizer
        Authorizers:
          ExternalAuthorizer:
            FunctionArn:
              Fn::ImportValue: ExternalAuthorizer
            EnableSimpleResponses: true
      CorsConfiguration: true
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      StageName: v4

  # http api with no auth and cors
  TestHttpApiv5:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: 'Authorization, *'
        AllowMethods: 'GET, POST, DELETE, *'
        AllowOrigins: 'http://localhost, https://stackoverflow.com'
        ExposeHeaders: 'Date, x-api-id'
        MaxAge: 100
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      StageName: v5

  # base layer for functions, this isn't used atm the handlers run against your dev dependencies instead
  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: base_layer
      Description: Base layer for containers
      ContentUri: base
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs14.x

  # a secret from secret manager, we don't do anything with this yet
  EncryptionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: my-secret
      Description: My Secret
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: "secretValue"
        ExcludeCharacters: '"@/\\'

  # functions
  pathParamTestGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.pathParamTestGet
      Events:
        Apiv1:
          Type: HttpApi
          Properties:
            Path: /{pathParam}/test/
            Method: get
            ApiId: !Ref TestHttpApiv1

  doublePathParamTestGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.doublePathParamTestGet
      Events:
        Apiv1:
          Type: HttpApi
          Properties:
            Path: /{pathParam1}/test/{pathParam2}/testagain
            Method: get
            ApiId: !Ref TestHttpApiv1

  testGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.testGet
      Events:
        Apiv1Get:
          Type: HttpApi
          Properties:
            Path: /test
            Method: get
            ApiId: !Ref TestHttpApiv1
        Apiv1Delete:
          Type: HttpApi
          Properties:
            Path: /test
            Method: delete
            ApiId: !Ref TestHttpApiv1
        Apiv2:
          Type: HttpApi
          Properties:
            Path: /test
            Method: get
            ApiId: !Ref TestHttpApiv2
        Apiv3:
          Type: HttpApi
          Properties:
            Path: /test
            Method: get
            ApiId: !Ref TestHttpApiv3
        Apiv5:
          Type: HttpApi
          Properties:
            Path: /test
            Method: get
            ApiId: !Ref TestHttpApiv5

  proxyTestGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.proxyTestGet
      Events:
        Apiv1:
          Type: HttpApi
          Properties:
            Path: /proxy/{proxy}+
            Method: get
            ApiId: !Ref TestHttpApiv1

  testPost:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.testPost
      Events:
        Apiv2:
          Type: HttpApi
          Properties:
            Path: /test
            Method: post
            ApiId: !Ref TestHttpApiv2

  scheduledPost:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.scheduledPost
      Events:
        Apiv2:
          Type: HttpApi
          Properties:
            Path: /scheduled
            Method: post
            ApiId: !Ref TestHttpApiv2
        EveryTenMinutes:
          Type: Schedule
          Properties:
            Schedule: 'rate(10 minutes)'
            Name: EveryTenMinutes
            Description: Run every 10 minutes
            Enabled: true

  # an authorizer function
  lambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.authorizer

  simpleLambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/v1/index.simpleAuthorizer

Outputs:
  TestHttpApiv1:
    Description: "API Gateway endpoint URL for test api v1"
    Value:
      Fn::Sub: https://${TestHttpApiv1}.execute-api.${AWS::Region}.amazonaws.com/v1
  TestHttpApiv2:
    Description: "API Gateway endpoint URL for test api v2"
    Value:
      Fn::Sub: https://${TestHttpApiv2}.execute-api.${AWS::Region}.amazonaws.com/v2
  TestHttpApiv3:
    Description: "API Gateway endpoint URL for test api v3"
    Value:
      Fn::Sub: https://${TestHttpApiv3}.execute-api.${AWS::Region}.amazonaws.com/v3
  TestHttpApiv4:
    Description: "API Gateway endpoint URL for test api v4"
    Value:
      Fn::Sub: https://${TestHttpApiv4}.execute-api.${AWS::Region}.amazonaws.com/v4
  TestHttpApiv5:
    Description: "API Gateway endpoint URL for test api v5"
    Value:
      Fn::Sub: https://${TestHttpApiv5}.execute-api.${AWS::Region}.amazonaws.com/v5
